dist: xenial
language: node_js
node_js:
- 8
deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: simulator-backend
  env: SimulatorBackend-env
  bucket_name: arn:aws:s3:::elasticbeanstalk-eu-north-1-378672856045
  skip_cleanup: true
  on:
    branch: production
  access_key_id:
    secure: UPRpAVvMeKBws9FyQ4q4oUQIn2kaTxcbLMhiiTaFrWrdiJL8JxamHJx/ICiW8l+99ZGXpKqt5wwrVvI+F/yw1HusiVWILx3Yf1czUVl3zKjnaVD9/01bTnM84sihwrd/oV6MdJa3TLA3DVEdzjQ1iq/niYAKlvo77cIjIau2kRSJtTpep8SWqz8t+7kcVbscuDLnGBmQqc/IyiEgXMlFpAmzXkdibmlLWcgVKsdWaDnZExtbjTTPE2J1alRmhOu++/FYwAWD1ureLpMsYd3QUTnoEy6AoSUV2ecp90SPjgBhOxhqUJhnS82exvtZkKLB0Sw0PGQnSqhh235qs6zfJO/JFzjOgfC0SEJojAuYsWK4zCCrbQ7BTR4jzR1Z55x4qikPjnhZsfw890wyiIN7dQkCAQKTOnLwPQph75TTnU0Ov5RpFdMjhJ0vbg6ojdSEMib6Oyj6ag4bpGyxESlCeBv4OnW78H5yhv+727kfJXm+NP9uALSpkb4ZZY/rn7CPa0n3J+5g8pcDGnvtA2ZSTzpdaL92OsNKR+zQaJa3Y7vptG1xJ6ypyBfnEnmSfeuhf7k7CmSRextAj0KVEuhwrXPNiRFu46itCetYzR8HCcGXB55YEDvK0PpCvdQEulLU6Pd+xyXLThNMCanXo07kLMFftx/WdvCR6qTr4IK8Fl8=
  secret_access_key:
    secure: j2A27RXI/RGDd4AiP2AjnXNUthf+kz7AvjlfJzhjcJ4zmd76rT/aSLH1an55hS9UmQNq/sdKTxasvoj03pUs9RD9uTO1h5tj3aRVXX5Gt00jUWRphQIRgBTxRIjFYLvb/whO77n2917FFN3tAGl/qi3+XdtHTwa3NYLSipctCilYFY6NTVZ8czdJ31PbkK8vJpXxJNv87QjFhcHfIxM37Qpi40BqDFtz5N/0UdVZQLOjTNqRYU/6qcYVieL68PabUyQCdBaiMoGYsJYjnkkTWPaoLKaBa35qMDymco7e6OGdiUCo47zmvhh57GjMqJ2lA8aSRy5ePoUn6TwQ2uh/msDwlt3H/8bNGrbahBexnQeIHprhzm76ii2ew8wHMxg2oBZk8vYJccpIRCksrGh6Er4wxt9X1DxRzGucLyypNVBpTzCJfcDYRdX1i36xATAAzvVinjt0SKiv2OFJC81wx50NbvVL4w5+Gi0DsX/TEbyQHlMbWLDS/OmUzd+1f1NJrvtRn+AKxo1srIbaGfdcsyDJl7vBOa6pMSTtxIKKz+G18MY80A+XT8YWa73ya2kLEIIGvZOug/KxfSoJ1vsytBracMTxIQsv15K6OjYPSmWv1CWuP0oFGLsuDfEPfZcKMkCZmsFfBnwbreh5ErsFTA0sUQoJSeXM1fPrWJ832co=
